spring.jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true

spring.datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://ec2-44-207-253-50.compute-1.amazonaws.com/d6iifip1fmsora
    username: xpbogeghcjyvqn
    password: 47ba2cfc473781de29c8242a7b73da7f04051cc0ce3b261c2b9c79326db931f4
    platform: postgres
    driver-class-name: org.postgresql.Driver
      
